# compile tailwindcss
build-css:
  npx tailwindcss -i {{justfile_directory()}}/tailwind/tailwind.src.css -o {{justfile_directory()}}/assets/css/tailwind.css -c {{justfile_directory()}}/tailwind/tailwind.config.js
