# compile tailwindcss
build-css: install-npm
  npx tailwindcss -i {{justfile_directory()}}/src/tailwind.src.css -o {{justfile_directory()}}/assets/css/tailwind.css -c {{justfile_directory()}}/src/tailwind.config.js
  npx postcss {{justfile_directory()}}/assets/css/tailwind.css --use autoprefixer --replace

# install npm dependencies
install-npm:
  npm ci {{justfile_directory()}}

# update npm dependencies
update-npm:
  npm install {{justfile_directory()}}
