name: Build and Release

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      - uses: Difegue/action-megacmd@master
        if: ${{ github.event_name == 'push' || env.ACT }}
        with:
          # gallery folder must be also named "galleries" on MEGA!
          # Will auto-merge remote folder with nikola folder
          args: get ${{secrets.GALLERY_MEGA_LINK}} ${{env.GITHUB_WORKSPACE}}
      # Make it reproducible with act
      # just action uses typescript which isn't supported
      # - uses: extractions/setup-just@v1
      - run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin --force
      - run: just --version
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if env.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          # This needs to be equal to the env name in the justfile!
          activate-environment: blog
          environment-file: env.yml
          use-only-tar-bz2: true # This needs to be set for caching to work
          # Note that pip depdencies aren't cached!
          miniforge-variant: Mambaforge
          use-mamba: true
      - run: just install-poetry
      - name: Test installation
        run: python -c "import nikola; print(nikola.__version__)"
      - name: build-site
        run: |
          just build-theme
          just build
      # just build will run the notebooks and cache the output of the notebooks
      # it will not, however, sync the file outputs of the runs!
      # this requires another build run to sync the output!
      - name: sync build-output
        run: just build
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Deploy to Server
        if: ${{ github.event_name == 'push' }}
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "output/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
